### ISSUE TITLE
Could you please upload the training code?

### ISSUE THREAD

**Issue by DLwbm123** [DeokyunKim/Progressive-Face-Super-Resolution#1]

**Comment by jiwoongim** [comment]
their trained model doesn't even work well

**Comment by DeokyunKim** [comment]
Thank you for your interest in our research. The uploaded model is trained using the aligned CelebA dataset. If you want to reconstruct low-resolution your own face images with our architecture, you need to re-train the model with your own dataset such as unaligned images, etc. 

We are trying to upload the training code. It is now delaying because this work is related to the company project. If you have more questions, please comment in here. Once again, we appreciate your interest!

**Comment by liushuangmax** [comment]
I think I have the same problem，Could you please upload the training code？？？

**Comment by DeokyunKim** [comment]
@DLwbm123  @liushuangmax  I uploaded training code. If you have more question, please reply to me. Thanks :)

**Comment by liushuangmax** [comment]
Thank you for your  reply .
| |
LShuangxx
|
|
lshuangxx@163.com
|
签名由网易邮箱大师定制
On 9/16/2019 13:53，DeokyunKim<notifications@github.com> wrote：

@DLwbm123@liushuangmax I uploaded training code. If you have more question, please reply to me. Thanks :)

**Comment by cyyycc** [comment]
> @DLwbm123@liushuangmax我上传了训练代码。如果您还有其他问题，请回复我。谢谢:)

I didn't see the training code in the project, could you upload it again? Thank you very much！
